name: Update Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate contribution graph
        uses: ashutosh00710/github-readme-activity-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "shivamchopra020403@gmail.com"
          git config --local user.name "Shivam Chopra"
          git add .
          git commit -m "Update contribution graph"
          git push
