name: Update Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-graph:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate contribution graph
        uses: nashvail/github-readme-activity-graph@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "shivamchopra020403@gmail.com"
          git config --local user.name "Shivam Chopra"
          git add .
          git commit -m "Update contribution graph" || echo "No changes to commit"
          git push
